version: 2
updates:
  # Enable version updates for graphql
  - package-ecosystem: 'npm'
    directory: '/graphql'
    schedule:
      interval: 'daily'

  # Enable version updates for scraper
  - package-ecosystem: 'pip'
    directory: '/scraper'
    schedule:
      interval: 'daily'

  # Enable version updates for ui
  - package-ecosyste: 'npm'
    directory: '/ui'
    schedule:
      interval: 'daily'
