version: 2
updates:
  # Updates for graphql npm
  - package-ecosystem: 'npm'
    directory: '/graphql'
    schedule:
      interval: 'daily'

  # Updates for graphql docker
  - package-ecosystem: 'docker'
    directory: '/graphql'
    schedule:
      interval: 'daily'

  # Updates for scraper pip
  - package-ecosystem: 'pip'
    directory: '/scraper'
    schedule:
      interval: 'daily'

  # Updates for scraper docker
  - package-ecosystem: 'docker'
    directory: '/scraper'
    schedule:
      interval: 'daily'

  # Updates for ui npm
  - package-ecosyste: 'npm'
    directory: '/ui'
    schedule:
      interval: 'daily'
