version: '3.7'

services:
  graphql:
    image: rs-graphql:dev
    container_name: rs-graphql
    ports:
      - 3000:3000
    environment:
      - REDDIT_CLIENT_ID=CHANGEME
      - REDDIT_CLIENT_SECRET=CHANGEME
      - REDDIT_USERNAME=CHANGEME
      - REDDIT_PASSWORD=CHANGEME
      - MONGO_USER=CHANGEME
      - MONGO_PASSWORD=CHANGEME
      - MONGO_URL=CHANGEME
      - MONGO_PROTOCOL=CHANGEME
