name: Anchore Container Scan - scraper

on:
  push:
    branches: [ main ]
    paths:
      - scraper/Dockerfile
  pull_request:
    branches: [ main ]
    paths:
      - scraper/Dockerfile
  schedule:
    - cron: '0 1 * * MON' # Every Monday.
  workflow_dispatch: # Manual trigger.

jobs:
  codacy-security-scan:
    name: Anchore Container Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ github.actor }}/scraper:latest
          context: ./scraper
          push: false
          load: true

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "zchryr/scraper:latest"